// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwfoYQ2fDdedxfVGV4jFY6_wANgm4M838',
    appId: '1:476947291063:web:0350f404ae46e426e0a632',
    messagingSenderId: '476947291063',
    projectId: 'tiktok-abc-xyz',
    authDomain: 'tiktok-abc-xyz.firebaseapp.com',
    storageBucket: 'tiktok-abc-xyz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqjB_ClOmAh_tEnIq3qDDbgWi2izP6Jzo',
    appId: '1:476947291063:android:36b0327a5d1f9145e0a632',
    messagingSenderId: '476947291063',
    projectId: 'tiktok-abc-xyz',
    storageBucket: 'tiktok-abc-xyz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBut0ecAdRTg-ootQAetxwQMayibUjs1AU',
    appId: '1:476947291063:ios:9ea83a901b668d25e0a632',
    messagingSenderId: '476947291063',
    projectId: 'tiktok-abc-xyz',
    storageBucket: 'tiktok-abc-xyz.appspot.com',
    iosClientId: '476947291063-qrcet8e2k6ooket4cgnhthv49l0mta1m.apps.googleusercontent.com',
    iosBundleId: 'co.nomadcoders.tiktok',
  );
}
